spring:
  datasource:
    url: jdbc:mysql://localhost:33061/demo?autoReconnect=true&serverTimezone=UTC
    username: root
    password: 'P@ssw0rd'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: INFO

server:
  port: 8080